/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author amjad
 */
public class FirstPanel extends javax.swing.JPanel {

    /**
     * Creates new form FirstPanel
     */
    public static settingFrame sp;
    public FirstPanel() {
        initComponents();
        setLayout(new BorderLayout());
        add(jLabel1,BorderLayout.CENTER);
        setSize(jLabel1.getSize());
       
          jButton4.setOpaque(false);
jButton4.setContentAreaFilled(false); //to make the content area transparent
jButton4.setBorderPainted(false);
          jButton3.setOpaque(false);
jButton3.setContentAreaFilled(false); //to make the content area transparent
jButton3.setBorderPainted(false);
        aa1.setLocation(1250, 50);
        aa2.setLocation(1250, 150);
        aa3.setLocation(1250, 250);
        aa4.setLocation(1250, 350);
        aa5.setLocation(1250, 450);
        
        aa4.setOpaque(false);
        aa4.setContentAreaFilled(false); //to make the content area transparent
        aa4.setBorderPainted(false);

        aa5.setOpaque(false);
        aa5.setContentAreaFilled(false); //to make the content area transparent
        aa5.setBorderPainted(false);

        aa3.setOpaque(false);
        aa3.setContentAreaFilled(false); //to make the content area transparent
        aa3.setBorderPainted(false);

        aa2.setOpaque(false);
        aa2.setContentAreaFilled(false); //to make the content area transparent
        aa2.setBorderPainted(false);

        aa1.setOpaque(false);
        aa1.setContentAreaFilled(false); //to make the content area transparent
        aa1.setBorderPainted(false);
    }
public class shi extends Thread
{
    public void run()
    {
        while(true)
        {
            if( aa1.getX()<1000)
                return;
                try 
            {
                Thread.sleep(1);
            } catch (InterruptedException ex) 
            {}
            aa1.setLocation(aa1.getX()-1, aa1.getY());    
        }
    }
}
    public class shi1 extends Thread
{
    public void run()
    {
        while(true)
        {
            if( aa2.getX()<1000)
                return;
                try 
            {
                Thread.sleep(2);
            } catch (InterruptedException ex) 
            {}
            aa2.setLocation(aa2.getX()-1, aa2.getY());      
        }
    }
    }
    public class shi2 extends Thread
{
    public void run()
    {
        while(true)
        {
            if( aa3.getX()<1000)
                return;
                try 
            {
                Thread.sleep(3);
            } catch (InterruptedException ex) 
            {}
           
            aa3.setLocation(aa3.getX()-1, aa3.getY());
        

                
        }
    }
    }
    public class shi3 extends Thread
{
    public void run()
    {
        while(true)
        {
            if( aa4.getX()<1000)
                return;
                try 
            {
                Thread.sleep(4);
            } catch (InterruptedException ex) 
            {}
           
            aa4.setLocation(aa4.getX()-1, aa4.getY());

                
        }
    }
    }
    public class shi4 extends Thread
{
    public void run()
    {
        while(true)
        {
            if( aa5.getX()<1000)
                return;
                try 
            {
                Thread.sleep(5);
            } catch (InterruptedException ex) 
            {}
           
            aa5.setLocation(aa5.getX()-1, aa5.getY());

                
        }
    }
    
    
    
    
    
    
    
    
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        aa3 = new javax.swing.JButton();
        aa2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        aa1 = new javax.swing.JButton();
        aa4 = new javax.swing.JButton();
        aa5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/mbp/NetBeansProjects/project/mclaren_720s_coupe_2017_4k-HD.jpg")); // NOI18N

        setSize(new java.awt.Dimension(15, 15));
        setLayout(null);

        aa3.setIcon(new javax.swing.ImageIcon("/Users/mbp/NetBeansProjects/project/speedometer_service_car_tachometer_traffic-256.png")); // NOI18N
        aa3.setRolloverIcon(new javax.swing.ImageIcon("/Users/mbp/NetBeansProjects/project/rol img/sss1.png")); // NOI18N
        aa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aa3ActionPerformed(evt);
            }
        });
        add(aa3);
        aa3.setBounds(520, 190, 80, 90);

        aa2.setIcon(new javax.swing.ImageIcon("/Users/mbp/NetBeansProjects/project/ssssss5.png")); // NOI18N
        aa2.setRolloverIcon(new javax.swing.ImageIcon("/Users/mbp/NetBeansProjects/project/rol img/aaa.png")); // NOI18N
        aa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aa2ActionPerformed(evt);
            }
        });
        add(aa2);
        aa2.setBounds(520, 120, 80, 80);

        jButton3.setIcon(new javax.swing.ImageIcon("/Users/mbp/NetBeansProjects/project/282467-256.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(20, 450, 150, 140);

        jButton4.setIcon(new javax.swing.ImageIcon("/Users/mbp/NetBeansProjects/project/f-right_256-128.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(170, 450, 140, 140);

        aa1.setIcon(new javax.swing.ImageIcon("/Users/mbp/NetBeansProjects/project/ssssss3.png")); // NOI18N
        aa1.setRolloverIcon(new javax.swing.ImageIcon("/Users/mbp/NetBeansProjects/project/rol img/a.png")); // NOI18N
        aa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aa1ActionPerformed(evt);
            }
        });
        add(aa1);
        aa1.setBounds(510, 10, 100, 100);

        aa4.setIcon(new javax.swing.ImageIcon("/Users/mbp/NetBeansProjects/project/ss.png")); // NOI18N
        aa4.setRolloverIcon(new javax.swing.ImageIcon("/Users/mbp/NetBeansProjects/project/rol img/ssss2.png")); // NOI18N
        aa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aa4ActionPerformed(evt);
            }
        });
        add(aa4);
        aa4.setBounds(520, 280, 80, 90);

        aa5.setIcon(new javax.swing.ImageIcon("/Users/mbp/NetBeansProjects/project/sssss4.png")); // NOI18N
        aa5.setRolloverIcon(new javax.swing.ImageIcon("/Users/mbp/NetBeansProjects/project/rol img/sssss4.png")); // NOI18N
        add(aa5);
        aa5.setBounds(520, 350, 80, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/mbp/NetBeansProjects/project/main img/fa61c8c4243772d412bea7a119c6e056.jpg")); // NOI18N
        jLabel1.setText("");
        add(jLabel1);
        jLabel1.setBounds(-20, 0, 710, 590);
    }// </editor-fold>//GEN-END:initComponents

    private void aa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aa3ActionPerformed


    }//GEN-LAST:event_aa3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       shi s=new shi();
       s.start();
       shi1 s1=new shi1();
       s1.start();
       shi2 s2=new shi2();
       s2.start();
       shi3 s3=new shi3();
       s3.start();
       shi4 s4=new shi4();
       s4.start();
     
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       UP.ff.setVisible(false);
        Project.f.setVisible(true);
         aa1.setLocation(1250, 50);
        aa2.setLocation(1250, 150);
        aa3.setLocation(1250, 250);
        aa4.setLocation(1250, 350);
        aa5.setLocation(1250, 450);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void aa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aa2ActionPerformed

    private void aa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aa4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aa4ActionPerformed

    private void aa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aa1ActionPerformed
sp=new settingFrame();
sp.setLocation(350, 350);
sp.setVisible(true);


    }//GEN-LAST:event_aa1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aa1;
    private javax.swing.JButton aa2;
    private javax.swing.JButton aa3;
    private javax.swing.JButton aa4;
    private javax.swing.JButton aa5;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
