/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author amjad
 */
public class LockScreenPanel extends javax.swing.JPanel {

    /**
     * Creates new form LockScreenPanel
     */
    public LockScreenPanel() {
     initComponents();
     setLayout(new BorderLayout());
     ImageIcon image = new ImageIcon("rentalbg1 (1).png");
     JLabel l = new JLabel(image);
     setSize(image.getIconWidth(),image.getIconHeight());
     
     add(l,BorderLayout.CENTER);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
