/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author amjad
 */


public class SettingPanel extends javax.swing.JPanel {

    /**
     * Creates new form SettingPanel
     */
    public static  AddAcount ac;
    public static settingFrame f;
    public SettingPanel() {
        initComponents();
        setSize(jLabel1.getSize());
         jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false); //to make the content area transparent
        jButton2.setBorderPainted(false);
        
      jButton3.setOpaque(false);
      jButton3.setContentAreaFilled(false); //to make the content area transparent
     jButton3.setBorderPainted(false);
         ac=new AddAcount();
         
         

    }
public class sh extends Thread
{
  public void run()
  {
      while(true)
      {
     
       if(ac.getX()==0)
           return;
          try{
              Thread.sleep(1);
              
          } catch (InterruptedException ex) {}
          ac.setLocation(ac.getX()+1, ac.getY());
      }
      
      
  }
    
    
}
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setLayout(null);
        add(jTextField1);
        jTextField1.setBounds(60, 100, 180, 18);
        add(jTextField2);
        jTextField2.setBounds(60, 170, 180, 18);
        add(jTextField3);
        jTextField3.setBounds(60, 240, 180, 18);
        add(jTextField4);
        jTextField4.setBounds(60, 300, 180, 18);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/mbp/NetBeansProjects/project/main img/boy-128.png")); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(20, 80, 36, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/mbp/NetBeansProjects/project/main img/icons_password-128.png")); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(20, 150, 35, 35);

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/mbp/NetBeansProjects/project/main img/Check_circle-256.png")); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(10, 220, 40, 40);

        jButton2.setIcon(new javax.swing.ImageIcon("/Users/mbp/NetBeansProjects/project/main img/stock_save.png")); // NOI18N
        add(jButton2);
        jButton2.setBounds(240, 370, 100, 100);

        jButton3.setIcon(new javax.swing.ImageIcon("/Users/mbp/NetBeansProjects/project/main img/undo-256.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(380, 370, 120, 100);

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/mbp/NetBeansProjects/project/main img/Wrong-128.png")); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(10, 280, 60, 50);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setText("add acount");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(40, 30, 94, 24);

        jButton4.setText("up date");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(130, 30, 74, 24);

        jButton5.setText("delete acount");
        add(jButton5);
        jButton5.setBounds(200, 30, 79, 24);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        add(jLabel1);
        jLabel1.setBounds(0, -40, 510, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FirstPanel.sp.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
      sh a=new sh();
      a.start();
      
        
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
